server {
    listen 80;
    server_name options.exclusivehub.link;

    root /var/www/options-moex;
    index index.html;

    location /iss/ {
        proxy_pass https://iss.moex.com/iss/;
        proxy_ssl_server_name on;
        proxy_set_header Host iss.moex.com;
        proxy_set_header User-Agent "Mozilla/5.0";
        proxy_hide_header Access-Control-Allow-Origin;
        add_header Access-Control-Allow-Origin *;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
